CREATE OR REPLACE VIEW geoserver.abs_stats_poly AS
SELECT area_id,
    area_type,
    tot_p_p,
    tot_p_p_sq_km,
    tot_p_p_sq_km_cl,
    tot_p_f,
    tot_p_f_sq_km,
    tot_p_f_sq_km_cl,
    tot_p_m,
    tot_p_m_sq_km,
    tot_p_m_sq_km_cl,
    indigenous_p_tot_p,
    indigenous_p_tot_p_sq_km,
    indigenous_p_tot_p_sq_km_cl,
    median_age_persons,
    median_age_persons_cl,
    median_rent_weekly,
    median_rent_weekly_cl,
    median_tot_prsnl_inc_weekly,
    median_tot_prsnl_inc_weekly_cl,
    average_household_size,
    average_household_size_cl,
    geom
FROM geoserver.abs_stats;

CREATE OR REPLACE VIEW geoserver.abs_stats_point AS
SELECT area_id,
    area_type,
    tot_p_p,
    tot_p_p_sq_km,
    tot_p_p_sq_km_cl,
    tot_p_f,
    tot_p_f_sq_km,
    tot_p_f_sq_km_cl,
    tot_p_m,
    tot_p_m_sq_km,
    tot_p_m_sq_km_cl,
    indigenous_p_tot_p,
    indigenous_p_tot_p_sq_km,
    indigenous_p_tot_p_sq_km_cl,
    median_age_persons,
    median_age_persons_cl,
    median_rent_weekly,
    median_rent_weekly_cl,
    median_tot_prsnl_inc_weekly,
    median_tot_prsnl_inc_weekly_cl,
    average_household_size,
    average_household_size_cl,
    centroid_geom as geom
FROM geoserver.abs_stats;
